// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/v1/tsrv/test.proto

package tsrv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a0419751309b28, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Response struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a0419751309b28, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "testsrv.v1.Request")
	proto.RegisterType((*Response)(nil), "testsrv.v1.Response")
}

func init() { proto.RegisterFile("pb/v1/tsrv/test.proto", fileDescriptor_95a0419751309b28) }

var fileDescriptor_95a0419751309b28 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4a, 0xc3, 0x40,
	0x18, 0x85, 0x99, 0x04, 0xb4, 0x4e, 0x41, 0xc2, 0x68, 0xa5, 0x54, 0x17, 0x25, 0xab, 0x52, 0x6d,
	0x86, 0xe8, 0x46, 0xea, 0x46, 0x8a, 0x0b, 0xd7, 0xd1, 0x95, 0xbb, 0x49, 0xf2, 0x13, 0x87, 0xa6,
	0x99, 0x64, 0xfe, 0xc9, 0x80, 0x5b, 0xaf, 0xe0, 0x31, 0x3c, 0x8e, 0x57, 0xf0, 0x20, 0x32, 0x53,
	0x45, 0x5d, 0x89, 0x9b, 0x9f, 0x9f, 0xc7, 0xe3, 0x7b, 0x8f, 0x47, 0x47, 0x6d, 0xce, 0x6d, 0xca,
	0x0d, 0x6a, 0xcb, 0x0d, 0xa0, 0x49, 0x5a, 0xad, 0x8c, 0x62, 0xd4, 0xfd, 0xa8, 0x6d, 0x62, 0xd3,
	0xc9, 0x49, 0xa5, 0x54, 0x55, 0x03, 0x17, 0xad, 0xe4, 0xa2, 0x69, 0x94, 0x11, 0x46, 0xaa, 0x06,
	0xb7, 0xce, 0xf8, 0x94, 0xee, 0x66, 0xd0, 0xf5, 0x80, 0x86, 0xed, 0xd3, 0x40, 0x96, 0x63, 0x32,
	0x25, 0xb3, 0x30, 0x0b, 0x64, 0xc9, 0x22, 0x1a, 0x6e, 0xb0, 0x1a, 0x07, 0x53, 0x32, 0xdb, 0xcb,
	0xdc, 0x1b, 0x9f, 0xd1, 0x41, 0x06, 0xd8, 0xaa, 0x06, 0xe1, 0x6f, 0xf7, 0xf9, 0x2b, 0xa1, 0xc3,
	0x7b, 0x40, 0x73, 0x07, 0xda, 0xca, 0x02, 0xd8, 0x2d, 0x0d, 0x35, 0x74, 0xec, 0x20, 0xf9, 0x2e,
	0x97, 0x7c, 0x66, 0x4f, 0x0e, 0x7f, 0x8b, 0xdb, 0x8c, 0xf8, 0xe8, 0xf9, 0xed, 0xfd, 0x25, 0x88,
	0xe2, 0xa1, 0x2f, 0x6f, 0x53, 0xae, 0xa1, 0x5b, 0x92, 0x39, 0xcb, 0xe8, 0x40, 0x43, 0x77, 0x03,
	0xb5, 0x78, 0xfa, 0x0f, 0xee, 0xd8, 0xe3, 0x46, 0x71, 0xf4, 0x03, 0x57, 0x3a, 0xc8, 0x92, 0xcc,
	0x57, 0xab, 0x87, 0xeb, 0x4a, 0x9a, 0xc7, 0x3e, 0x4f, 0x0a, 0xb5, 0xe1, 0x5a, 0x94, 0x12, 0xad,
	0xa8, 0x65, 0x5f, 0xd7, 0xb2, 0xf1, 0xd3, 0x2e, 0x4a, 0x55, 0xac, 0x41, 0x2f, 0xd6, 0x97, 0xc8,
	0xfd, 0x76, 0x5f, 0x14, 0x97, 0x73, 0xe5, 0x4e, 0xbe, 0xe3, 0xf5, 0x8b, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2c, 0x20, 0xa6, 0x9c, 0x96, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	Req(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ReqDelay(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Req(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/testsrv.v1.TestService/req", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) ReqDelay(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/testsrv.v1.TestService/reqDelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	Req(context.Context, *Request) (*Response, error)
	ReqDelay(context.Context, *Request) (*Response, error)
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_Req_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Req(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testsrv.v1.TestService/Req",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Req(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_ReqDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ReqDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testsrv.v1.TestService/ReqDelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ReqDelay(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testsrv.v1.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "req",
			Handler:    _TestService_Req_Handler,
		},
		{
			MethodName: "reqDelay",
			Handler:    _TestService_ReqDelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/v1/tsrv/test.proto",
}
