apiVersion: v1
kind: Pod
metadata:
  name: test-docker-k8s-pod
  labels:
    app: test-docker-k8s-app
spec:
  containers:
  - name: test-docker-k8s-cont
    image: test-docker-k8s
    imagePullPolicy: Never
    command: ['sh', '-c', '/go/src/github.com/radisvaliullin/test-docker-k8s/bin/srv']
